version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  mysql:
    container_name: julo.mysql
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_USER=julo
      - MYSQL_PASSWORD=julo
      - MYSQL_DATABASE=julo
      - MYSQL_ROOT_PASSWORD=Root#123
      - TZ=UTC
    image: mysql:5.7
    networks:
      - app-network
    ports: 
      - 33066:3306/tcp
    restart: unless-stopped
    volumes:
      - app-data:/var/lib/mysql

  backend:
    command: ./startup.sh
    depends_on:
      - mysql
    build: .
    image: julo:local
    container_name: julo.backend
    # volumes:
    #   - .:/var/www
    networks:
      app-network:
    ports:
      - 80:80/tcp
